=== enxl/mgpd/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns="http://www.uniovi.es"
	targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud-circuito" />
				<xs:element ref="anchura-media" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="origen" />
				<xs:element ref="puntos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />

	<xs:simpleType name="longitudPositiva">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="tipoLongitudCircuito">
		<xs:simpleContent>
			<xs:extension base="longitudPositiva">
				<xs:attribute name="unidades" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="tipoAnchuraMedia">
		<xs:simpleContent>
			<xs:extension base="longitudPositiva">
				<xs:attribute name="unidades" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:element name="longitud-circuito" type="tipoLongitudCircuito" />
	<xs:element name="anchura-media" type="tipoAnchuraMedia" />

	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:positiveInteger" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="title" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:positiveInteger" />

	<!-- Estos tipos definen la restricciones de longitud y latitud -->
	<xs:simpleType name="longitudDecimal">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180" />
			<xs:maxInclusive value="180" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="latitudDecimal">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90" />
			<xs:maxInclusive value="90" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="tipoLongitud">
		<xs:simpleContent>
			<xs:extension base="longitudDecimal">
				<xs:attribute name="unidades" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="tipoLatitud">
		<xs:simpleContent>
			<xs:extension base="latitudDecimal">
				<xs:attribute name="unidades" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="tipoAltitud">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unidades" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:element name="longitud" type="tipoLongitud" />
	<xs:element name="latitud" type="tipoLatitud" />
	<xs:element name="altitud" type="tipoAltitud" />

	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="vencedor">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="tiempo" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="clasificado" />
				<xs:element ref="clasificado" />
				<xs:element ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== enxl/mgpd/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
    <nombre>Sachsenring</nombre>
    <longitud-circuito unidades="metros">3671</longitud-circuito>
    <anchura-media unidades="metros">12</anchura-media>
    <fecha>2025-07-13</fecha>
    <hora>14:00:00</hora>
    <vueltas>30</vueltas>
    <localidad>Oberlungwitz</localidad>
    <pais>Alemania</pais>
    <patrocinador>Liqui Moly</patrocinador>
    <referencias>
        <referencia title="Artículo en Wikipedia">https://en.wikipedia.org/wiki/2025_German_motorcycle_Grand_Prix</referencia>
        <referencia title="Descubre Sachsenring">
            https://rtrsports.com/es/blog/descubre-el-sachsenring-corazon-de-la-velocidad-alemana/</referencia>
        <referencia title="Datos de interés de Sachsenring">https://www.redbull.com/es-es/datos-de-interes-sachsenring</referencia>
    </referencias>
    <fotografias>
        <fotografia alt="Vista aérea del circuito de Sachsenring">multimedia/sachsenring1.jpg</fotografia>
        <fotografia alt="Podio del Gran Premio de Sachsenring 2025">multimedia/sachsenring2.jpg</fotografia>
        <fotografia alt="Parrilla de salida del Gran Premio de Sachsenring">multimedia/sachsenring3.jpg</fotografia>
    </fotografias>
    <videos>
        <video>multimedia/sachsenring.mp4</video>
    </videos>
    <origen>
        <coordenadas>
            <longitud unidades="grados">12.68806933735892</longitud>
            <latitud unidades="grados">50.79176536132668</latitud>
            <altitud unidades="metros">330.9769986160285</altitud>
        </coordenadas>
    </origen>
    <puntos>
        <punto>
            <distancia unidades="metros">0.000</distancia>
            <coordenadas>
                <longitud unidades="grados">12.6837746866335</longitud>
                <latitud unidades="grados">50.7899238008232</latitud>
                <altitud unidades="metros">318.7914853793927</altitud>
            </coordenadas>
            <sector>3</sector>
        </punto>
        <punto>
            <distancia unidades="metros">315.996</distancia>
            <coordenadas>
                <longitud unidades="grados">12.68806933735892</longitud>
                <latitud unidades="grados">50.79176536132668</latitud>
                <altitud unidades="metros">330.9769986160285</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">43.905</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69181264026193</longitud>
                <latitud unidades="grados">50.79333860742232</latitud>
                <altitud unidades="metros">335.518300789748</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">45.421</distancia>
            <coordenadas>
                <longitud unidades="grados">12.6923337711424</longitud>
                <latitud unidades="grados">50.79324285282432</latitud>
                <altitud unidades="metros">334.5677473700879</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">96.926</distancia>
            <coordenadas>
                <longitud unidades="grados">12.6924548179506</longitud>
                <latitud unidades="grados">50.79284276245513</latitud>
                <altitud unidades="metros">331.5663175396471</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">73.577</distancia>
            <coordenadas>
                <longitud unidades="grados">12.6917787731443</longitud>
                <latitud unidades="grados">50.79216330544996</latitud>
                <altitud unidades="metros">328.0204529791458</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">95.984</distancia>
            <coordenadas>
                <longitud unidades="grados">12.6920638329247</longitud>
                <latitud unidades="grados">50.79146510679245</latitud>
                <altitud unidades="metros">324.1862701536473</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">69.318</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69313858990349</longitud>
                <latitud unidades="grados">50.7910870662244</latitud>
                <altitud unidades="metros">317.254748045503</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">102.791</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69304473211175</longitud>
                <latitud unidades="grados">50.79045715534304</latitud>
                <altitud unidades="metros">314.7827123580818</altitud>
            </coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidades="metros">63.622</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69219010675903</longitud>
                <latitud unidades="grados">50.79054543026174</latitud>
                <altitud unidades="metros">317.3521910062796</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">143.992</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69170259782964</longitud>
                <latitud unidades="grados">50.79129237891836</latitud>
                <altitud unidades="metros">324.7342519490529</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">154.710</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69060350554998</longitud>
                <latitud unidades="grados">50.79163494453566</latitud>
                <altitud unidades="metros">330.2893863185779</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">115.794</distancia>
            <coordenadas>
                <longitud unidades="grados">12.68952790241969</longitud>
                <latitud unidades="grados">50.79115216190096</latitud>
                <altitud unidades="metros">334.7728659216579</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">157.769</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69026225624556</longitud>
                <latitud unidades="grados">50.78989670235472</latitud>
                <altitud unidades="metros">325.6256818888209</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">312.036</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69143353043994</longitud>
                <latitud unidades="grados">50.78950007499506</latitud>
                <altitud unidades="metros">319.5759390187782</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">227.411</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69286467636916</longitud>
                <latitud unidades="grados">50.78975609388839</latitud>
                <altitud unidades="metros">312.7040709982618</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">224.129</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69553469926564</longitud>
                <latitud unidades="grados">50.79145652884571</latitud>
                <altitud unidades="metros">314.0169093370825</altitud>
            </coordenadas>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidades="metros">256.541</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69403418458663</longitud>
                <latitud unidades="grados">50.79342114526214</latitud>
                <altitud unidades="metros">333.394923821135</altitud>
            </coordenadas>
            <sector>3</sector>
        </punto>
        <punto>
            <distancia unidades="metros">818.174</distancia>
            <coordenadas>
                <longitud unidades="grados">12.69226890849724</longitud>
                <latitud unidades="grados">50.79384309055703</latitud>
                <altitud unidades="metros">337.1767218330701</altitud>
            </coordenadas>
            <sector>3</sector>
        </punto>
        <punto>
            <distancia unidades="metros">74.503</distancia>
            <coordenadas>
                <longitud unidades="grados">12.6896048312526</longitud>
                <latitud unidades="grados">50.79289950535738</latitud>
                <altitud unidades="metros">334.0722355090545</altitud>
            </coordenadas>
            <sector>3</sector>
        </punto>
        <punto>
            <distancia unidades="metros">44.391</distancia>
            <coordenadas>
                <longitud unidades="grados">12.68267891674745</longitud>
                <latitud unidades="grados">50.79311116849347</latitud>
                <altitud unidades="metros">304.5250482717951</altitud>
            </coordenadas>
            <sector>3</sector>
        </punto>
        <punto>
